---
version: "3.8"
services:
  teia-docs:
    build: .
    restart: unless-stopped
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - ./.github/workflows/nginx.conf:/etc/nginx/conf.d/default.conf
